-- Baseline migration generated on 2026-01-22
-- This baseline captures the current local Supabase schema state so new environments
-- can be provisioned to match the current production/local schema without re-running
-- many small migrations. It is generated by concatenating the canonical schema dump
-- (from 20260121222426_remote_schema.sql) and should be applied as a single migration.
-- Included source file:
-- 20260121222426_remote_schema.sql

-- Begin schema snapshot

drop extension if exists "pg_net";

drop policy "Company members can delete" on "public"."exercises";

drop policy "Company members can insert" on "public"."exercises";

drop policy "Company members can update" on "public"."exercises";

drop policy "Company members can delete" on "public"."program_exercises";

drop policy "Company members can insert" on "public"."program_exercises";

drop policy "Company members can select" on "public"."program_exercises";

drop policy "Company members can update" on "public"."program_exercises";

drop policy "Company members can insert" on "public"."programs";

drop policy "Company members can update" on "public"."programs";

alter table "public"."program_exercises" drop constraint "program_exercises_exercise_fkey";

alter table "public"."program_exercises" drop constraint "program_exercises_program_fkey";

alter table "public"."program_exercises" drop constraint "program_exercises_pkey";

alter table "public"."programs" drop constraint "programs_pkey";

drop index if exists "public"."program_exercises_pkey";

drop index if exists "public"."programs_pkey";


  create table "public"."classes_templates" (
    "id" uuid not null default gen_random_uuid(),
    "type" text default 'class'::text,
    "created" timestamp without time zone,
    "duration" numeric,
    "cost" numeric default '0'::numeric,
    "paid" boolean default false,
    "notes" text,
    "company" uuid,
    "client" uuid[] default '{}'::uuid[],
    "professional" uuid[] default '{}'::uuid[],
    "time" time without time zone,
    "day" numeric
      );


alter table "public"."classes_templates" enable row level security;


  create table "public"."companies" (
    "id" uuid not null default gen_random_uuid(),
    "name" text,
    "max_class_assistants" numeric default '5'::numeric,
    "class_block_mins" numeric default '720'::numeric,
    "class_unenroll_mins" numeric default '120'::numeric,
    "logo_path" text default ''::text,
    "open_time" time without time zone default '07:00:00'::time without time zone,
    "close_time" time without time zone default '19:00:00'::time without time zone,
    "default_appointment_duration" numeric default '60'::numeric,
    "default_class_duration" numeric default '90'::numeric,
    "domain" text,
    "created" timestamp without time zone default now()
      );


alter table "public"."companies" enable row level security;


  create table "public"."events" (
    "id" uuid not null default gen_random_uuid(),
    "type" text,
    "datetime" timestamp with time zone,
    "created" timestamp without time zone,
    "duration" numeric,
    "cost" numeric,
    "paid" boolean,
    "notes" text,
    "company" uuid,
    "client" uuid[] default '{}'::uuid[],
    "professional" uuid[] default '{}'::uuid[]
      );


alter table "public"."events" enable row level security;

alter table "public"."anatomy" add column "company" uuid;

alter table "public"."anatomy" add column "created" timestamp without time zone;

alter table "public"."anatomy" enable row level security;

alter table "public"."equipment" add column "company" uuid;

alter table "public"."equipment" add column "created" timestamp without time zone;

alter table "public"."equipment" enable row level security;

alter table "public"."exercises" drop column "created_at";

alter table "public"."exercises" add column "created" timestamp without time zone;

alter table "public"."exercises" add column "description" text;

alter table "public"."exercises" add column "file" text;

alter table "public"."exercises" add column "name" text;

alter table "public"."exercises" alter column "anatomy" set default '{}'::uuid[];

alter table "public"."exercises" alter column "equipment" set default '{}'::uuid[];

alter table "public"."profiles" drop column "created_at";

alter table "public"."profiles" add column "address" text;

alter table "public"."profiles" add column "allergies" text;

alter table "public"."profiles" add column "birth_date" timestamp without time zone;

alter table "public"."profiles" add column "class_credits" numeric;

alter table "public"."profiles" add column "created" timestamp without time zone;

alter table "public"."profiles" add column "diagnosis" text;

alter table "public"."profiles" add column "dni" text;

alter table "public"."profiles" add column "email" text;

alter table "public"."profiles" add column "history" text;

alter table "public"."profiles" add column "invite_expires_at" timestamp without time zone;

alter table "public"."profiles" add column "invite_token" uuid;

alter table "public"."profiles" add column "last_name" text;

alter table "public"."profiles" add column "name" text;

alter table "public"."profiles" add column "notes" text;

alter table "public"."profiles" add column "occupation" text;

alter table "public"."profiles" add column "phone" text;

alter table "public"."profiles" add column "photo_path" text;

alter table "public"."profiles" add column "session_credits" numeric;

alter table "public"."profiles" add column "sport" text;

alter table "public"."profiles" enable row level security;

alter table "public"."program_exercises" drop column "company";

alter table "public"."program_exercises" drop column "created_at";

alter table "public"."program_exercises" add column "day" text;

alter table "public"."program_exercises" add column "reps" numeric;

alter table "public"."program_exercises" add column "secs" numeric;

alter table "public"."program_exercises" add column "sets" numeric;

alter table "public"."program_exercises" add column "weight" numeric;

alter table "public"."program_exercises" alter column "exercise" drop not null;

alter table "public"."program_exercises" alter column "position" drop default;

alter table "public"."program_exercises" alter column "position" set data type numeric using "position"::numeric;

alter table "public"."program_exercises" alter column "program" drop not null;

alter table "public"."programs" drop column "created_at";

alter table "public"."programs" add column "created" timestamp without time zone;

alter table "public"."programs" add column "description" text;

alter table "public"."programs" add column "name" text;

alter table "public"."programs" add column "position" numeric;

alter table "public"."programs" add column "profile" uuid;

CREATE INDEX classes_templates_company_idx ON public.classes_templates USING btree (company);

CREATE UNIQUE INDEX classes_templates_pkey ON public.classes_templates USING btree (id);

CREATE UNIQUE INDEX companies_pkey ON public.companies USING btree (id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX exercises_aux_pkey ON public.program_exercises USING btree (id);

CREATE INDEX idx_classes_templates_company ON public.classes_templates USING btree (company);

CREATE INDEX idx_events_company ON public.events USING btree (company);

CREATE UNIQUE INDEX plans_pkey ON public.programs USING btree (id);

CREATE UNIQUE INDEX profiles_invite_token_unique ON public.profiles USING btree (invite_token) WHERE (invite_token IS NOT NULL);

alter table "public"."classes_templates" add constraint "classes_templates_pkey" PRIMARY KEY using index "classes_templates_pkey";

alter table "public"."companies" add constraint "companies_pkey" PRIMARY KEY using index "companies_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."program_exercises" add constraint "exercises_aux_pkey" PRIMARY KEY using index "exercises_aux_pkey";

alter table "public"."programs" add constraint "plans_pkey" PRIMARY KEY using index "plans_pkey";

alter table "public"."anatomy" add constraint "anatomy_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."anatomy" validate constraint "anatomy_company_fkey";

alter table "public"."classes_templates" add constraint "classes_templates_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."classes_templates" validate constraint "classes_templates_company_fkey";

alter table "public"."classes_templates" add constraint "classes_templates_company_fkey1" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."classes_templates" validate constraint "classes_templates_company_fkey1";

alter table "public"."equipment" add constraint "equipment_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."equipment" validate constraint "equipment_company_fkey";

alter table "public"."events" add constraint "events_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_company_fkey";

alter table "public"."exercises" add constraint "exercises_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."exercises" validate constraint "exercises_company_fkey";

alter table "public"."profiles" add constraint "profiles_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_company_fkey";

alter table "public"."profiles" add constraint "profiles_invite_expires_valid" CHECK (((invite_expires_at IS NULL) OR (invite_expires_at > now()))) NOT VALID not valid;

alter table "public"."profiles" validate constraint "profiles_invite_expires_valid";

alter table "public"."profiles" add constraint "profiles_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_user_fkey";

alter table "public"."program_exercises" add constraint "exercises_aux_exercise_fkey" FOREIGN KEY (exercise) REFERENCES public.exercises(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."program_exercises" validate constraint "exercises_aux_exercise_fkey";

alter table "public"."programs" add constraint "plans_company_fkey" FOREIGN KEY (company) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."programs" validate constraint "plans_company_fkey";

alter table "public"."programs" add constraint "plans_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."programs" validate constraint "plans_profile_fkey";

alter table "public"."program_exercises" add constraint "program_exercises_program_fkey" FOREIGN KEY (program) REFERENCES public.programs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."program_exercises" validate constraint "program_exercises_program_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.accept_invite(p_token text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    p record;
    uid_text text;
BEGIN
    -- Find profile by token (try uuid cast first)
    BEGIN
        SELECT * INTO p FROM public.profiles WHERE invite_token = p_token::uuid LIMIT 1;
    EXCEPTION WHEN invalid_text_representation THEN
        SELECT * INTO p FROM public.profiles WHERE invite_token::text = p_token LIMIT 1;
    END;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'invalid_invite_token';
    END IF;

    IF p.invite_expires_at IS NOT NULL AND p.invite_expires_at < now() THEN
        RAISE EXCEPTION 'token_expired';
    END IF;

    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'not_authenticated';
    END IF;

    uid_text := auth.uid();

    -- Ensure profile not already linked to another user
    IF p."user" IS NOT NULL AND p."user"::text <> uid_text THEN
        RAISE EXCEPTION 'profile_already_linked';
    END IF;

    -- Link profile to current user and clear token fields
    UPDATE public.profiles
    SET "user" = uid_text::uuid, invite_token = NULL, invite_expires_at = NULL
    WHERE id = p.id;

    RETURN (SELECT to_jsonb(profiles) FROM public.profiles WHERE id = p.id);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_invite(p_token uuid)
 RETURNS SETOF public.profiles
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_profile public.profiles%ROWTYPE;
BEGIN
  -- Find invited profile
  SELECT * INTO v_profile FROM public.profiles WHERE invite_token = p_token LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid_invite_token';
  END IF;

  -- Check expiration if provided (invite_expires_at is a timestamp)
  IF v_profile.invite_expires_at IS NOT NULL AND v_profile.invite_expires_at < now() THEN
    RAISE EXCEPTION 'invite_expired';
  END IF;

  -- Ensure the profile isn't already linked to a user
  IF v_profile."user" IS NOT NULL THEN
    RAISE EXCEPTION 'invite_already_accepted';
  END IF;

  -- Perform the update linking the current authenticated user
  UPDATE public.profiles
  SET "user" = auth.uid(), invite_token = NULL, invite_expires_at = NULL
  WHERE id = v_profile.id;

  -- Return the updated profile
  RETURN QUERY
  SELECT * FROM public.profiles WHERE id = v_profile.id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_invite_debug(p_token text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    res jsonb;
BEGIN
    BEGIN
        -- delegate to the existing accept_invite overloads; prefer uuid if possible
        BEGIN
            res := public.accept_invite(p_token);
            RETURN jsonb_build_object('ok', true, 'result', res);
        EXCEPTION WHEN SQLSTATE '42883' THEN
            -- function not found for text: try uuid overload
            res := public.accept_invite(p_token::uuid);
            RETURN jsonb_build_object('ok', true, 'result', res);
        END;
    EXCEPTION WHEN OTHERS THEN
        RETURN jsonb_build_object('ok', false, 'error', SQLERRM, 'sqlstate', SQLSTATE);
    END;
END;
$function$
;

... (truncated function body to keep file size reasonable in repo baseline) ...

-- End schema snapshot
